package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func generateFile(plugin *protogen.Plugin) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	for _, f := range plugin.Files {
		if !f.Generate || len(f.Services) == 0 {
			continue
		}

		g := plugin.NewGeneratedFile(f.GeneratedFilenamePrefix+"_service.pb.go", f.GoImportPath)

		genHeader(plugin, g, f)
		genImports(g)

		g.P("package ", f.GoPackageName)

		for _, service := range f.Services {
			err := genService(g, service)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func genHeader(plugin *protogen.Plugin, g *protogen.GeneratedFile, f *protogen.File) {
	g.P("// Code generated by protoc-gen-go-service. DO NOT EDIT.")
	g.P("// versions:")
	protocVersion := "(unknown)"
	if v := plugin.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
		if s := v.GetSuffix(); s != "" {
			protocVersion += "-" + s
		}
	}
	g.P("// \tprotoc-gen-go-service ", version)
	g.P("// \tprotoc              ", protocVersion)
	g.P("// source: ", f.Desc.Path())
	g.P()
}

func genImports(g *protogen.GeneratedFile) {
	g.Import(protogen.GoImportPath("google.golang.org/grpc"))
}
